apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonconsumerreactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonconsumerreactions
  template:
    metadata:
      labels:
        app: pythonconsumerreactions
    spec:
      containers:
      - image: docker.io/xmnvasquez/pythonconsumerreactions:{github.sha}
        name: pythonconsumerreactions
#        envFrom:
#        - configMapRef:
#            name: adsoftsito-config
#        livenessProbe:
#          httpGet:
#            path: /ht/
#            port: 8080
#          initialDelaySeconds: 5
#          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: pythonconsumerreactions
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "pythonconsumerreactions"
    port: 8081
  selector:
    app: pythonconsumerreactions

